fix: eliminate redundant profile dirs and streamline repo target

diff --git a/.github/workflows/W1700K.yaml b/.github/workflows/W1700K.yaml
--- a/.github/workflows/W1700K.yaml
+++ b/.github/workflows/W1700K.yaml
@@ -42,9 +42,8 @@ jobs:
       run: |
         curl --fail -Z --create-dirs -Lo user/default/files/etc/apk/repositories.d/distfeeds.list https://w1700k.github.io/builds/distfeeds.list
         curl --fail -Z -Lo user/default/files/etc/vermagic.txt https://w1700k.github.io/builds/vermagic.txt
-        [ -f "user/${{ matrix.target }}/config.diff" ] || [ -f "user/default/config.diff" ] || { echo "::error::config.diff not found"; exit 1; }
+        [ -f "user/default/config.diff" ] || { echo "::error::config.diff not found"; exit 1; }
         rsync -aI --mkpath user/default/ user/current/ 2>&-
-        rsync -aI --mkpath user/${{ matrix.target }}/ user/current/ 2>&-
         echo 'CONFIG_CCACHE_DIR="/ghcache"' >> user/current/config.diff
         sudo tee /etc/docker/daemon.json <<< '{"max-concurrent-downloads":50,"max-concurrent-uploads":50,"experimental":true}'
         sudo systemctl reload docker
@@ -60,8 +59,8 @@ jobs:
     - name: Prepare OpenWrt source
       run: |
         docker_exec DK bash -e -c '
-          . $DK_PROFILE/settings.ini
-          [[ $REPO_URL && $REPO_BRANCH ]] || { echo "::error::Missing REPO_URL or REPO_BRANCH"; exit 1; }
+          REPO_URL="https://github.com/OpenWRT-fanboy/OpenW1700k"
+          REPO_BRANCH="${{ matrix.target }}"
           mkdir -p $DK_OPENWRT/files
           cd $DK_OPENWRT
           if [ ! -d .git ]; then git init; fi
